### ISSUE TITLE
Fails when checking code with `eslint-disable` comments of unknown rules.

### ISSUE THREAD

**Issue by brabeji** [robatwilliams/es-compat#100]
When trying to determine which library causes check-es-compat to fail, it's necessary to run it on unminified code. This code can contain `eslint-disable` disabling rule unknown to `es-compat`.

```
// eslint-disable-next-line @typescript-eslint/no-explicit-any
function _eventFromIncompleteOnError(msg, url, line, column) {
...
```

This causes to fail with `Definition for rule not found`.

**Comment by robatwilliams** [comment]
Interesting, thanks for reporting.

It seems this has come up with ESLint before in https://github.com/eslint/eslint/issues/14851, but no action was taken.

I think using `noInlineConfig` in the CLI code should stop it - https://eslint.org/docs/latest/use/configure/rules#disabling-inline-comments https://github.com/robatwilliams/es-compat/blob/master/packages/check-es-compat/bin/cli.mjs

You could try that quickly by modifying the file in your node_modules.

**Comment by brabeji** [comment]
@robatwilliams haha I'm just in the middle of creating a PR, just a sec.

**Comment by brabeji** [comment]
> I think using noInlineConfig in the CLI code should stop it

That indeed worked. 👍

**Comment by robatwilliams** [comment]
Released in https://github.com/robatwilliams/es-compat/releases/tag/v3.2.1

thanks
