### ISSUE TITLE
warning  File ignored because of a matching ignore pattern

### ISSUE THREAD

**Issue by dobesv** [robatwilliams/es-compat#23]
When I run it I get these warnings:

```
/home/ubuntu/app/dist/web/vnd.timers-browserify.js
  0:0  warning  File ignored because of a matching ignore pattern. Use "--no-ignore" to override
```

It seems to be applying the rules from `.eslintignore`.  It might be nice if I could use `--no-ignore` as suggested, but that option is not propagated through by the command line tool.

**Comment by robatwilliams** [comment]
Need to pass `ignore: false` when constructing CLIEngine. Already passing an option to ignore eslintrc files.

https://eslint.org/docs/developer-guide/nodejs-api#cliengine

**Comment by robatwilliams** [comment]
Released https://github.com/robatwilliams/es-compat/releases/tag/v1.1.1
