### ISSUE TITLE
Tool does not disable all other plugins and rules

### ISSUE THREAD

**Issue by dobesv** [robatwilliams/es-compat#25]
I noticed warnings printed from other rules / plugins that I don't want:

```
/home/ubuntu/app/dist/web/vnd.draft-js-plugins-editor.js
  429:3   error  Definition for rule 'react/no-unused-prop-types' was not found  react/no-unused-prop-types
  850:1   error  Definition for rule 'import/no-named-as-default' was not found  import/no-named-as-default
```

**Comment by robatwilliams** [comment]
That's unexpected, when the CLIEngine [is constructed](https://github.com/robatwilliams/es-compat/blob/master/packages/check-es-compat/bin/cli.js#L22), we pass `useEslintrc: false` so it should ignore all your config files.

https://eslint.org/docs/developer-guide/nodejs-api#cliengine

**Comment by dobesv** [comment]
Indeed.  Also, I don't get the impression it is applying all the rules, just some of them.  Very odd.

**Comment by robatwilliams** [comment]
I can't reproduce this. It's definitely not looking in any eslintrc file; I checked with an invalid file and it didn't complain.

Can you share more detail and/or try to narrow down the problem and provide a reproduction?

**Comment by dobesv** [comment]
I tried to modify your "example" file to add the same eslint plugins I am using but to no avail, it still didn't report these issues.

I'll close this for now, and reopen it if I have time to revisit this in more detail later.
