### ISSUE TITLE
Update eslint plugin to use new @mdn/browser-compat-data package

### ISSUE THREAD

**Issue by m-allanson** [robatwilliams/es-compat#28]
Installing and running this just now gave me a deprecation warning:

```
(node:28542) DeprecationWarning: mdn-browser-compat-data is deprecated. Upgrade to @mdn/browser-compat-data. Learn more: https://github.com/mdn/browser-compat-data/blob/v1.1.0/UPGRADE-2.0.x.md
```

From the usage in [`features/es2016.js`](https://github.com/robatwilliams/es-compat/blob/5cbf4aebc3ff93ae9bf770a3d265bd8a845f85a8/packages/eslint-plugin-ecmascript-compat/lib/features/es2016.js#L3).

**Comment by robatwilliams** [comment]
@m-allanson thanks for reporting, fixed in v2.0.0 - just released
