### ISSUE TITLE
(Are you using this project ?)

### ISSUE THREAD

**Issue by robatwilliams** [robatwilliams/es-compat#51]
I'd be interest to hear, however little you can say.

Knowing people are using this certainly helps my ongoing decision to spend time on it.

**Comment by robatwilliams** [comment]
Like this message if you're using it but can't or don't want to say anything.

**Comment by zloirock** [comment]
I don't use it, however, I monitor it since it's a good concept and with some improvements like https://github.com/robatwilliams/es-compat/pull/50 it could be useful for my cases.

**Comment by dingtwo** [comment]
I used this project and it helped me solve the malfunction that occurred in the production environment. I think this project is great. 
My next plan is to integrate this project into my CI process as a check.
Thank you.
