### ISSUE TITLE
Sustainability of continued dependency on mysticatea/eslint-plugin-es

### ISSUE THREAD

**Issue by robatwilliams** [robatwilliams/es-compat#52]
The last commit and interaction on the project was over 2 years ago. The author is still active on GitHub but hasn't responded to attempts by people to contact them.

* Blocks enhancements for newer ES versions, unless we implement rules from scratch (#44)
* Lack of fixes for possible bugs and compatibility issues with newer ESLint versions
* Generally bad things about depending on an abandoned project

The author has been invited to transfer the repo to the eslint-community organisation: https://github.com/mysticatea/eslint-plugin-es/issues/92

**Comment by zloirock** [comment]
https://github.com/ota-meshi/eslint-plugin-es-x is a properly maintained fork.

**Comment by robatwilliams** [comment]
The above fork has now become https://github.com/eslint-community/eslint-plugin-es-x

**Comment by robatwilliams** [comment]
Released https://github.com/robatwilliams/es-compat/releases/tag/v3.0.0

now using the fork
