### ISSUE TITLE
Private methods and private fields separation

### ISSUE THREAD

**Issue by jonathanKingston** [robatwilliams/es-compat#79]
Currently it appears there is not ability to disambiguate between class fields and class methods (please correct me if I'm wrong).

**Rationale**

- https://caniuse.com/mdn-javascript_classes_private_class_methods is a very different support table than https://caniuse.com/mdn-javascript_classes_private_class_fields
- For example WebView 83 is still pretty common for Android.

**Comment by robatwilliams** [comment]
The plugin is using https://eslint-community.github.io/eslint-plugin-es-x/rules/no-class-fields.html whose scope includes methods and fields (full list seen in their test source).

In my [join-up](https://github.com/robatwilliams/es-compat/blob/8a3f9fed7faddfe720c2eb59bbe604d8bf8e3b5d/packages/eslint-plugin-ecmascript-compat/lib/features/es2022.js#L18C47-L18C62) of that rule with compat DB features, I have only referred to fields - which is a bug.

To enable distinguishing, the es-x plugin's rule would need splitting, or a custom one written here. I can't see them splitting it for this use case.

**Comment by robatwilliams** [comment]
Bug part of this needs fixing, but the enhancement won't be due to limitation of no-class-fields as described above.
