### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by lukeapage** [robatwilliams/es-compat#81]
Hi Robat,

I'm after this commit:
https://github.com/robatwilliams/es-compat/commit/00be9823e5909607c1c8992a5bad36cfd1a6fc5a

but it isn't published.. is it possible to make a new release?

**Comment by robatwilliams** [comment]
Hi

This fix is for #71 

IIRC I didn't release as it was just something I'd noticed.

I should be able to release easily enough as this is the only non-tooling/docs change since v3.

**Comment by robatwilliams** [comment]
Released https://github.com/robatwilliams/es-compat/releases/tag/v3.0.1
