### ISSUE TITLE
Missing some polyfill options

### ISSUE THREAD

**Issue by lukeapage** [robatwilliams/es-compat#82]
BigInt, SharedArrayBuffer can come up as errors but no option exists to polyfill them

**Comment by robatwilliams** [comment]
BigInt was discussed in #70

I expect SharedArrayBuffer is the same in that it cannot be polyfilled in the browser.

Would #72 solve your issue?

**Comment by lukeapage** [comment]
Thanks for the quick reply, I will follow the other issue.
